export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_UPDATE_PROJECTS = 'GET_UPDATE_PROJECTS'
export const POST_PROJECT = 'POST_PROJECT'
export const PUT_PROJECT = 'PUT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const SELECT_PROJECT = 'SELECT_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'

export const GET_NOTES = 'GET_NOTES'
export const GET_UPDATE_NOTES = 'GET_UPDATE_NOTES'
export const POST_NOTE = 'POST_NOTE'
export const PUT_NOTE = 'PUT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const NOTES_ERROR = 'NOTES_ERROR'

export const SELECT_NOTE = 'SELECT_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
